services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - script.painless.regex.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 4096
      nofile: 65536
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      retries: 5
      timeout: 5s
  seed:
    image: seed
    build:
      context: ./seed_image
      args:
        ES_URL: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: /bin/sh
    command: >
      -c "python populate_es_indices.py"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 127.0.0.1:5601:5601
    depends_on:
      - elasticsearch
  search_recommend_api:
    build:
      context: .
      args:
        ES_URL: http://elasticsearch:9200
      dockerfile: search_recommend_api/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - elasticsearch
  tests:
    build:
      context: .
      args:
        ES_URL: http://elasticsearch:9200
      dockerfile: tests/Dockerfile
    depends_on:
      elasticsearch:
        condition: service_healthy
      seed:
        condition: service_completed_successfully
    entrypoint: /bin/sh
    command: >
      -c "pytest --cov /app/tests/"